/**
 * \file list-player-flags.h
 * \brief player race and class flags
 *
 * Adjusting these flags does not break savefiles. Flags below start from 1
 * on line 14, so a flag's sequence number is its line number minus 13.
 *
 * Fields:
 * symbol - the flag name
 * additional details in player_property.txt
 */

PF(NONE)
PF(FAST_SHOT)
PF(BRAVERY_30)
PF(BLESS_WEAPON)
PF(ZERO_FAIL)
PF(BEAM)
PF(CHOOSE_SPELLS)
PF(KNOW_MUSHROOM)
PF(KNOW_ZAPPER)
PF(SEE_ORE)
PF(NO_MANA)
PF(CHARM)
PF(UNLIGHT)
PF(ROCK)
PF(STEAL)
PF(SHIELD_BASH)
PF(EVIL)
PF(COMBAT_REGEN)
PF(NO_FOOD)
PF(NO_SWIMMING)
PF(EAT_BATTERIES)
PF(GREEDY)
PF(NO_TIME_LIMIT)
PF(REROLL_MUTATIONS)
PF(NO_MUTATIONS)
PF(FLY_ANY_TIME)

/* Abilities - Super */
PF(FLIGHT)
PF(TORCH)
PF(SUPER_STRENGTH)
PF(SUPER_SPEED)
PF(FREEZE_RAY)
PF(HEAT_RAY)
PF(LASER_EYE)
PF(RADIATE)
PF(GIANT)
PF(BEAR)
PF(X_RAY_VISION)
PF(MESMERIZE)
PF(BANISH)
PF(LASSO)
PF(FIFTH_DIMENSION)
PF(EARTHBENDING)

/* Abilities - general talents */
PF(FORAGING)
PF(PRECOCITY)
PF(PATIENCE)
PF(UNKNOWN_TALENTS)
PF(EMOTIONAL_INTELLIGENCE)
PF(TRADE_CONNECTION)
PF(MOB_CONNECTION)
PF(NET_CONNECTION)

PF(CAVESPEEDER_PILOT)
PF(CAVEFIGHTER_PILOT)
PF(CAVERACER_PILOT)
PF(CAVELINER_PILOT)

/* Marksman specialties */
PF(HANDGUN_SPECIALIST)
PF(RIFLE_SPECIALIST)
PF(6MM_HANDGUN_SPECIALIST)
PF(9MM_HANDGUN_SPECIALIST)
PF(12MM_HANDGUN_SPECIALIST)
PF(6MM_RIFLE_SPECIALIST)
PF(9MM_RIFLE_SPECIALIST)
PF(12MM_RIFLE_SPECIALIST)

/* Mutations */
PF(PUKING)

PF(SPIT_ACID)
PF(HORNS)
PF(KNOB_HEAD)

/* Physique */
PF(THICK_MUSCLES)
PF(LEAN_AND_FRAGILE)
PF(SPRINTER)

/* Eyes */
PF(COMPOUND_EYES)
PF(WIDE_EYES)
PF(CAT_EYES)

/* Mental */
PF(ANIMAL_MAGNETISM)
PF(THICK_BRAIN)

/* Skin */
PF(ELEPHANT_HIDE)
PF(CRYSTAL_SKIN)
PF(SCALY_SKIN)
PF(STEEL_SKIN)
PF(STONE_SKIN)
